export const names = [
    "Aakash Shrivastava",
    "Abhishek Srivastava",
    "Aditya Mundra",
    "Afzal Ahmed",
    "Ajay Singh",
    "Amit (Webiance)",
    "Amit Barui",
    "Amrita Ganguly",
    "Ankita Jethi",
    "Arpan Tibrewal",
    "Arpit Pandey",
    "Burhanuddin Barwani",
    "Chaitanya Pathak",
    "Chirag Joshi",
    "Dhananjay Jha",
    "Dhaval",
    "Dr.Dhruv Thakkar",
    "Gaurav Gupte",
    "Harshit Chaturvedi",
    "Ishu agarwal",
    "Jayant R",
    "Kavita Agrawal",
    "KP Singh",
    "Madhav Kumar",
    "Mahavir Prashad",
    "Mohammed yaser",
    "Namrataa Bhatia",
    "Nilansh Chandna",
    "Nirmit Sinha Goel",
    "Nishant Arya",
    "Nivedita Gogia",
    "Pallabi Mishra",
    "Payal chitkara",
    "Payal Khuran",
    "Pradeep Negi",
    "Puneeth K M",
    "Purti Singh",
    "Rahul Jassoria",
    "Rajesh Madan",
    "Rashmi Suthar",
    "Rishabh Arora",
    "Rittik Bansal",
    "Rushikesh Marathe",
    "Sachin Kumar",
    "Saurabh Kumar Singh",
    "Savi Jain",
    "Shikha Bokar",
    "Shikha Khanna",
    "Shubham Satkar",
    "Shyantani Chowdhury",
    "Snehal Patel",
    "Sudhakar Kumar",
    "Sukhmeen kaur",
    "Sumit Dewangan",
    "Tanmay Desai",
    "Tauseeef Hasan",
    "Vishal Shah",
    "Yogesh Panwar",
    "Krishan Pandey",
    "Fatema Hussain"
  ];
  